// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: peerlist.proto

package ctrlmesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_Zero      MessageType = 0
	MessageType_Hello     MessageType = 1
	MessageType_FullState MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "Zero",
		1: "Hello",
		2: "FullState",
	}
	MessageType_value = map[string]int32{
		"Zero":      0,
		"Hello":     1,
		"FullState": 2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_peerlist_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_peerlist_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_peerlist_proto_rawDescGZIP(), []int{0}
}

type HelloMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *HelloMessage) Reset() {
	*x = HelloMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peerlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloMessage) ProtoMessage() {}

func (x *HelloMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peerlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloMessage.ProtoReflect.Descriptor instead.
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return file_peerlist_proto_rawDescGZIP(), []int{0}
}

func (x *HelloMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HelloMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PeerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ads     []string `protobuf:"bytes,2,rep,name=ads,proto3" json:"ads,omitempty"`
	Updated uint32   `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *PeerMessage) Reset() {
	*x = PeerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peerlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage) ProtoMessage() {}

func (x *PeerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peerlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage.ProtoReflect.Descriptor instead.
func (*PeerMessage) Descriptor() ([]byte, []int) {
	return file_peerlist_proto_rawDescGZIP(), []int{1}
}

func (x *PeerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerMessage) GetAds() []string {
	if x != nil {
		return x.Ads
	}
	return nil
}

func (x *PeerMessage) GetUpdated() uint32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type FullStateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []*PeerMessage `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *FullStateMessage) Reset() {
	*x = FullStateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peerlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullStateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullStateMessage) ProtoMessage() {}

func (x *FullStateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peerlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullStateMessage.ProtoReflect.Descriptor instead.
func (*FullStateMessage) Descriptor() ([]byte, []int) {
	return file_peerlist_proto_rawDescGZIP(), []int{2}
}

func (x *FullStateMessage) GetPeers() []*PeerMessage {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_peerlist_proto protoreflect.FileDescriptor

var file_peerlist_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x65, 0x65, 0x72, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x65, 0x73, 0x68, 0x22, 0x38, 0x0a, 0x0c, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x0b, 0x50, 0x65, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22,
	0x3f, 0x0a, 0x10, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x50, 0x65,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73,
	0x2a, 0x31, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x5a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x10, 0x02, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x7a, 0x69, 0x74, 0x69, 0x2d, 0x69, 0x6e, 0x63, 0x75, 0x62,
	0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x65, 0x73, 0x68, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_peerlist_proto_rawDescOnce sync.Once
	file_peerlist_proto_rawDescData = file_peerlist_proto_rawDesc
)

func file_peerlist_proto_rawDescGZIP() []byte {
	file_peerlist_proto_rawDescOnce.Do(func() {
		file_peerlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_peerlist_proto_rawDescData)
	})
	return file_peerlist_proto_rawDescData
}

var file_peerlist_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peerlist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_peerlist_proto_goTypes = []interface{}{
	(MessageType)(0),         // 0: ctrlmesh.MessageType
	(*HelloMessage)(nil),     // 1: ctrlmesh.HelloMessage
	(*PeerMessage)(nil),      // 2: ctrlmesh.PeerMessage
	(*FullStateMessage)(nil), // 3: ctrlmesh.FullStateMessage
}
var file_peerlist_proto_depIdxs = []int32{
	2, // 0: ctrlmesh.FullStateMessage.peers:type_name -> ctrlmesh.PeerMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_peerlist_proto_init() }
func file_peerlist_proto_init() {
	if File_peerlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_peerlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peerlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peerlist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullStateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peerlist_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peerlist_proto_goTypes,
		DependencyIndexes: file_peerlist_proto_depIdxs,
		EnumInfos:         file_peerlist_proto_enumTypes,
		MessageInfos:      file_peerlist_proto_msgTypes,
	}.Build()
	File_peerlist_proto = out.File
	file_peerlist_proto_rawDesc = nil
	file_peerlist_proto_goTypes = nil
	file_peerlist_proto_depIdxs = nil
}
